import csv, random, datetime, os
random.seed(42)

OUT_DIR = "data"
os.makedirs(OUT_DIR, exist_ok=True)
OUT_FILE = os.path.join(OUT_DIR, "transactions.csv")

categories = {
  "Coffee/Dining": [
    "coffee",
    "café",
    "cafe",
    "starbucks",
    "costa coffee",
    "barista",
    "coffee day",
    "ccd",
    "espresso",
    "latte",
    "cappuccino",
    "mocha",
    "brew",
    "coffee shop",
    "bean",
    "coffee bean",
    "dunkin",
    "dunkin donuts",
    "tim hortons",
    "blue tokai",
    "aroma cafe",
    "coffee roasters",
    "caffeine",
    "restaurant",
    "dine",
    "dining",
    "food court",
    "eatery",
    "bistro",
    "diner",
    "grill",
    "buffet",
    "barbeque",
    "bbq",
    "tandoor",
    "tandoori",
    "kitchen",
    "canteen",
    "mess",
    "lounge",
    "food joint",
    "fine dining",
    "thali",
    "dhaba",
    "trattoria",
    "resto-bar",
    "restobar",
    "resto lounge",
    "gastropub",
    "mcdonald",
    "mcdonald’s",
    "mcd",
    "kfc",
    "burger king",
    "subway",
    "pizza hut",
    "domino",
    "domino’s",
    "taco bell",
    "five guys",
    "wendy",
    "hardee",
    "papa john",
    "california pizza kitchen",
    "chipotle",
    "panda express",
    "jollibee",
    "barbeque nation",
    "mainland china",
    "urban tadka",
    "chili’s",
    "olive bistro",
    "cream centre",
    "sizzler",
    "lunchbox",
    "eatfit",
    "behrouz biryani",
    "biryani blues",
    "paradise",
    "tea",
    "chai",
    "chaayos",
    "chai point",
    "milkshake",
    "smoothie",
    "juice",
    "juicery",
    "frappe",
    "cold coffee",
    "snacks",
    "samosa",
    "sandwich",
    "bakery",
    "cake",
    "pastry",
    "dessert",
    "ice cream",
    "gelato",
    "donut",
    "waffle",
    "pancake",
    "bar",
    "pub",
    "tavern",
    "brewery",
    "microbrewery",
    "wine",
    "whisky",
    "beer",
    "cocktail",
    "mocktail",
    "nightclub",
    "taproom",
    "eat",
    "meal",
    "brunch",
    "breakfast",
    "lunch",
    "dinner",
    "takeaway",
    "take-out",
    "order",
    "ordering",
    "delivery",
    "table booking",
    "dine-in"
  ],
    "Shopping": [
    "shopping",
    "shop",
    "store",
    "mall",
    "supermarket",
    "hypermarket",
    "bazaar",
    "mart",
    "market",
    "outlet",
    "showroom",
    "retail",
    "fashion",
    "clothing",
    "apparel",
    "garment",
    "boutique",
    "footwear",
    "shoe",
    "sneaker",
    "jeans",
    "tshirt",
    "kurta",
    "dress",
    "handbag",
    "purse",
    "wallet",
    "watch",
    "accessory",
    "jewellery",
    "cosmetics",
    "perfume",
    "beauty",
    "makeup",
    "salon",
    "spa",
    "electronics",
    "mobile",
    "phone",
    "laptop",
    "computer",
    "tv",
    "television",
    "gadget",
    "camera",
    "headphone",
    "earphone",
    "speaker",
    "charger",
    "tech store",
    "home decor",
    "furniture",
    "bed",
    "sofa",
    "chair",
    "table",
    "lamp",
    "cushion",
    "curtain",
    "home center",
    "homecentre",
    "ikea",
    "big bazaar",
    "reliance trends",
    "reliance digital",
    "reliance smart",
    "smart bazaar",
    "dmart",
    "vishal mega mart",
    "more megastore",
    "spencer",
    "food bazaar",
    "lifestyle",
    "central",
    "pantaloons",
    "shoppers stop",
    "max fashion",
    "westside",
    "h&m",
    "zara",
    "nike",
    "adidas",
    "puma",
    "reebok",
    "woodland",
    "bata",
    "decathlon",
    "myntra",
    "ajio",
    "nykaa",
    "meesho",
    "snapdeal",
    "amazon",
    "flipkart",
    "ebay",
    "etsy",
    "aliexpress",
    "shein",
    "club factory",
    "jiomart",
    "bigbasket",
    "blinkit",
    "zepto",
    "grofers",
    "reliance fresh",
    "spencers retail",
    "vijay sales",
    "croma",
    "poorvika",
    "sangeetha mobiles",
    "unicorn store",
    "apple store",
    "samsung store",
    "xiaomi store",
    "mi home",
    "oneplus store",
    "lenovo exclusive",
    "canon store",
    "lenskart",
    "specsmakers",
    "optical store",
    "bookstore",
    "crossword",
    "oxford bookstore",
    "stationery",
    "gift shop",
    "toy store",
    "baby shop",
    "kidswear",
    "pet shop",
    "sports shop",
    "sportswear",
    "gymwear",
    "departmental store",
    "general store",
    "local market",
    "flea market",
    "online store",
    "order",
    "delivery",
    "cart",
    "checkout",
    "purchase",
    "retail outlet"
  ],
    "Fuel": [
    "fuel",
    "petrol",
    "diesel",
    "gas",
    "cng",
    "lpg",
    "ev charging",
    "charging station",
    "refueling",
    "refill",
    "gas station",
    "petrol bunk",
    "fuel pump",
    "service station",
    "energy station",
    "auto gas",
    "power station",
    "battery charging",
    "electric vehicle",
    "charge point",
    "hp petrol pump",
    "hpcl",
    "hindustan petroleum",
    "bharat petroleum",
    "bpcl",
    "indian oil",
    "ioc",
    "reliance petrol",
    "shell",
    "esso",
    "totalenergies",
    "total",
    "caltex",
    "mobil",
    "chevron",
    "gulf",
    "essar",
    "nayara",
    "petrocanada",
    "petro canada",
    "sunoco",
    "arco",
    "bp",
    "exxon",
    "exxonmobil",
    "murco",
    "petronas",
    "q8",
    "omv",
    "jet fuel",
    "gasoline",
    "kerosene",
    "diesel station",
    "fuel depot",
    "oil company",
    "fuel service",
    "vehicle fuel",
    "auto fuel",
    "car fuel",
    "motor fuel",
    "refuelling",
    "filling station",
    "hp station",
    "bp station",
    "ioc station",
    "fuel expenses",
    "highway fuel",
    "pump",
    "garage",
    "car wash",
    "auto care",
    "vehicle service",
    "fuel outlet",
    "fuel stop"
  ],
    "Groceries": [
    "grocery",
    "groceries",
    "supermarket",
    "hypermarket",
    "provision store",
    "general store",
    "kirana",
    "mart",
    "bazaar",
    "market",
    "minimart",
    "food store",
    "convenience store",
    "organic store",
    "daily needs",
    "essentials",
    "ration",
    "fresh produce",
    "vegetable",
    "fruit",
    "fruits",
    "veggies",
    "greens",
    "organic",
    "dairy",
    "milk",
    "bread",
    "butter",
    "cheese",
    "egg",
    "eggs",
    "ghee",
    "paneer",
    "snacks",
    "biscuits",
    "chips",
    "chocolates",
    "sweets",
    "namkeen",
    "cereal",
    "rice",
    "wheat",
    "atta",
    "flour",
    "pulses",
    "dal",
    "oil",
    "sugar",
    "salt",
    "spices",
    "masala",
    "tea",
    "coffee powder",
    "detergent",
    "soap",
    "shampoo",
    "toothpaste",
    "toiletries",
    "household",
    "cleaning",
    "detergent",
    "dishwash",
    "sanitary",
    "baby food",
    "pet food",
    "frozen food",
    "ready to eat",
    "packaged food",
    "instant noodles",
    "grocer",
    "local grocery",
    "corner shop",
    "neighborhood store",
    "reliance fresh",
    "reliance smart",
    "smart bazaar",
    "dmart",
    "big bazaar",
    "more megastore",
    "spencers",
    "easyday",
    "star bazaar",
    "spar",
    "nature’s basket",
    "bigbasket",
    "jiomart",
    "blinkit",
    "zepto",
    "grofers",
    "amazon fresh",
    "flipkart supermart",
    "spencers retail",
    "nilgiris",
    "24 seven",
    "foodworld",
    "reliance smart point",
    "hypercity",
    "more supermarket",
    "vishal mega mart",
    "loose items",
    "ration shop",
    "sahakari store",
    "food market",
    "farmers market",
    "fresh market",
    "daily mart",
    "weekly bazaar",
    "local mart",
    "super bazaar",
    "organic india",
    "whole foods",
    "fresho",
    "smart store",
    "neighborhood mart",
    "household essentials",
    "grocery delivery",
    "online grocery",
    "home delivery",
    "daily groceries",
    "monthly ration"
  ],
    "Travel": [
    "travel",
    "trip",
    "journey",
    "vacation",
    "holiday",
    "tour",
    "tourism",
    "getaway",
    "itinerary",
    "transport",
    "transportation",
    "transit",
    "ticket",
    "booking",
    "reservation",
    "flight",
    "airline",
    "airport",
    "airfare",
    "air ticket",
    "air travel",
    "plane",
    "jet",
    "indigo",
    "air india",
    "vistara",
    "spicejet",
    "goair",
    "akasa air",
    "emirates",
    "qatar airways",
    "etihad",
    "singapore airlines",
    "lufthansa",
    "british airways",
    "airasia",
    "thai airways",
    "malaysia airlines",
    "expedia",
    "skyscanner",
    "makemytrip",
    "yatra",
    "goibibo",
    "cleartrip",
    "ixigo",
    "ease my trip",
    "travelguru",
    "kayak",
    "hopper",
    "tripadvisor",
    "agoda",
    "booking.com",
    "airbnb",
    "oyo",
    "trivago",
    "treebo",
    "fabhotels",
    "stayzilla",
    "hostelworld",
    "oyo rooms",
    "oyo life",
    "oyo hotel",
    "taj hotels",
    "marriott",
    "hilton",
    "radisson",
    "hyatt",
    "lemontree",
    "ibis",
    "novotel",
    "ginger",
    "resort",
    "villa",
    "bnb",
    "homestay",
    "guesthouse",
    "lodge",
    "camping",
    "glamping",
    "bus",
    "train",
    "railway",
    "indian railways",
    "irctc",
    "metro",
    "local train",
    "shatabdi",
    "rajdhani",
    "vande bharat",
    "redbus",
    "abhibus",
    "intrcity",
    "flixbus",
    "cab",
    "taxi",
    "ola",
    "uber",
    "rapido",
    "in-driver",
    "meru cabs",
    "quickride",
    "blablacar",
    "zoomcar",
    "revolt ride",
    "bounce",
    "drivezy",
    "self drive",
    "bike rental",
    "car rental",
    "vehicle rental",
    "airport taxi",
    "hotel",
    "lodge booking",
    "stay",
    "stay booking",
    "accommodation",
    "room booking",
    "guest house",
    "travel insurance",
    "visa",
    "passport",
    "immigration",
    "foreign exchange",
    "currency exchange",
    "forex",
    "suitcase",
    "baggage",
    "luggage",
    "car hire",
    "tour package",
    "holiday package",
    "sightseeing",
    "adventure trip",
    "trekking",
    "cruise",
    "ship",
    "boat",
    "ferry",
    "travel agency",
    "travel agent",
    "transport service",
    "tour operator",
    "rental car",
    "rent a car",
    "rental bike",
    "pickup drop",
    "ride share",
    "journey ticket",
    "bus station",
    "train station",
    "hotel stay",
    "airport lounge",
    "metro card",
    "travel pass",
    "toll",
    "toll plaza",
    "fastag",
    "highway travel",
    "road trip",
    "intercity",
    "interstate",
    "fuel stop (travel)",
    "onroad",
    "travel expense"
  ],
  "Entertainment": [
    "entertainment",
    "movie",
    "cinema",
    "film",
    "theatre",
    "theater",
    "multiplex",
    "pvr",
    "inox",
    "cinepolis",
    "miraj cinema",
    "carnival cinema",
    "bookmyshow",
    "paytm movies",
    "ticketnew",
    "movie ticket",
    "film city",
    "drama",
    "show",
    "live show",
    "concert",
    "event",
    "festival",
    "standup",
    "comedy",
    "music",
    "song",
    "album",
    "spotify",
    "gaana",
    "wynk",
    "jiosaavn",
    "youtube music",
    "apple music",
    "amazon music",
    "soundcloud",
    "music app",
    "audio",
    "playlist",
    "radio",
    "fm",
    "stream",
    "streaming",
    "ott",
    "netflix",
    "amazon prime",
    "prime video",
    "disney plus",
    "hotstar",
    "hbo max",
    "sonyliv",
    "zee5",
    "voot",
    "mx player",
    "aha",
    "altbalaji",
    "eros now",
    "hulu",
    "peacock tv",
    "paramount plus",
    "apple tv",
    "jio cinema",
    "hoichoi",
    "movies app",
    "tv show",
    "web series",
    "subscription",
    "gaming",
    "game",
    "video game",
    "online game",
    "mobile game",
    "pc game",
    "playstation",
    "xbox",
    "steam",
    "epic games",
    "ea play",
    "nintendo",
    "pubg",
    "free fire",
    "call of duty",
    "valorant",
    "roblox",
    "fortnite",
    "ludo king",
    "dream11",
    "mpl",
    "game store",
    "gaming app",
    "play pass",
    "google play",
    "apple app store",
    "subscription service",
    "premium plan",
    "membership",
    "online event",
    "virtual concert",
    "ticket",
    "entertainment tax",
    "theme park",
    "amusement park",
    "fun city",
    "snow world",
    "escape room",
    "bowling",
    "pool",
    "casino",
    "club",
    "nightclub",
    "karaoke",
    "sports event",
    "stadium",
    "match ticket",
    "ipl ticket",
    "football match",
    "movie subscription",
    "video streaming",
    "entertainment store",
    "comic",
    "manga",
    "anime",
    "crunchyroll",
    "gaming subscription",
    "arcade",
    "virtual reality",
    "vr game",
    "cinema hall",
    "movie pass",
    "festival pass"
  ]
}

merchant_noises = [" ONLINE", " POS", " *", " TXN", " ECOM", "MOBILE"]
def noisy_merchant(m):
    if random.random() < 0.3:
        return m + random.choice(merchant_noises)
    if random.random() < 0.15:
        return m.replace(" ", "").upper()
    return m

def gen_datetime():
    year = 2025
    month = random.randint(1, 10)
    day = random.randint(1, 28)
    hour = random.randint(0, 23)
    minute = random.randint(0, 59)
    return datetime.datetime(year, month, day, hour, minute).isoformat(sep=' ')

N = 30000
with open(OUT_FILE, "w", newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(["id", "user_id", "datetime", "merchant", "amount", "label"])
    for i in range(1, N+1):
        label = random.choice(list(categories.keys()))
        merchant = random.choice(categories[label])
        merchant = noisy_merchant(merchant)
        amount = round(random.uniform(10, 5000), 2)
        user_id = random.randint(1, 200)  
        w.writerow([i, user_id, gen_datetime(), merchant, amount, label])

print(f"✅ Generated {OUT_FILE} with {N} rows")
